### ISSUE TITLE
Alphabetize Comic Books Section

### ISSUE THREAD

**Issue by thejessleigh** [sindresorhus/awesome-scifi#228]
The comic books section doesn't seem to be organized. It should be alphabetized by title.

**Comment by RichardLitt** [comment]
Agreed! Fancy making a PR?

**Comment by thejessleigh** [comment]
Sure thing! Just wanted to run it by the team first. I'll do that tonight.

**Comment by sindresorhus** [comment]
Why? I'm genuinely curious. I get this request a lot and nobody seems to have an actual reason for why. Awesome lists are for discovering new things, not looking up something you already know, so having it sorted alphabetically doesn't seem to have any clear advantage.

**Comment by RichardLitt** [comment]
That's a really good question!

I don't think that awesome lists are entirely about discovering new things - or, rather, that the process of discovery isn't as clear cut as just seeing items you don't know. For instance, if I were to come at this list with new eyes, I would wonder - is Lord of the Rings on here? Is Y, the Last Man (a relevant, awesome comic)? If I was looking at the ToC, I may (I'm not going to say _would_) scan the ToC for the appropriate entry, there. Knowing the schema used for ordering can be helpful, here. 

As well, when adding to this list, it is less easy to make a mistake by adding a duplicate if I know exactly where in the list an item ought to go. In that case, I can clearly see - "Oh, it's already there."

I think it comes down to knowing that humans are inherently lazy, and using schemas to sort and identify information is something we excel at doing (to a certain depth - obviously, we're bad at seeing things in SQL databases). Sticking to those schemas can have some benefits in recall. 

I can think of only one benefit to having an unordered list - you don't need to tell people to alphabetize their PRs. However, I think putting the onus on the entrants instead of on the much larger number of readers is better. 

This is a weak argument, overall, though! I think you're right - there's no solid reason why (although I would say that my reasoning would qualify as an actual reason). Again, really good question.

**Comment by thejessleigh** [comment]
That's totally fair. I think that putting things is alphabetical order does 2 things

1. It doesn't imply ranking one item over another, which can inadvertently happen when you have a list with no set ordering
2. It's consistent and makes it easier to contribute to the list without fear of accidentally introducing above implied hierarchy. 

Additionally, the contribution guidelines specify alphabetical order, and the other sections seem to follow this convention (more or less), so it's weird to have comic books be the outlier here.

**Comment by thejessleigh** [comment]
I also acknowledge that this isn't the strongest argument in the world. But I think introducing consistency slightly reduces friction for people adding to the list, and I think @RichardLitt's point about quickly identifying duplicates is solid.

However, I'm not a hardliner and this isn't my repo. I'll defer to whatever the core group decides 😄
