### ISSUE TITLE
Add "The Quantum Thief"?

### ISSUE THREAD

**Issue by heinrich-ulbricht** [sindresorhus/awesome-scifi#323]
I recently read **The Quantum Thief** by Hannu Rajaniemi and liked it very much. In terms of category - might be Biopunk? Don't know but worth to add to the overall list.

**Comment by RichardLitt** [comment]
Hmm. Put it where you think it fits best.

**Comment by Potherca** [comment]
Because I'd like to improve the odds of this being added (or I might add it myself once I've read it) I looked at what category reputable sources place this book in.

Sadly, most of those sources do not have categories like "Biopunk" or "Techno Thriller" :disappointed: 

That aside, looking at Amazon, Goodreads, Google Books, and ISFDB the most common entries (other than "sci-fi") are "Cyberpunk" and "Space Opera".

So at least that narrows things down a bit further.

<details><summary>Expand to see full listing</summary>

- [Amazon](https://www.amazon.com/Quantum-Thief-Jean-Flambeur-Book-ebook/dp/B004ULPVN6) "Best Sellers Rank"
  >  2,381 in Space Opera
  >    741 in Galactic Empire
  >    616 in Cyberpunk

- [Goodreads](https://www.goodreads.com/work/shelves/9886333-the-quantum-thief) "shelves"
  > science-fiction 1,230 people
  > sci-fi          1,045 people
  > cyberpunk         141 people
  > space-opera       100 people

- [Internet Speculative Fiction Database (ISFDB)](https://www.isfdb.org/cgi-bin/title.cgi?1105067) "tags"

  > science fiction (3)
  > mars (2)
  > space opera (2)

- Relevant [Google Books](https://www.google.nl/books/edition/The_Quantum_Thief/OXn7KJtG07UC?hl=en&gbpv=0) "subjects"
  > - Cyberpunk
  > - Genetic Engineering
  > - Hard Science Fiction
  > - Space Exploration 

</details>

**Comment by Potherca** [comment]
I'm currently in the process of reading the third book in the series. The "Jean Le Flambeur" universe is reminiscent of some of Neal Stephenson worlds. Falls squarely under Cyberpunk. Might make a write-up and MR when finished reading...
