### ISSUE TITLE
Order of synopsis / commentary

### ISSUE THREAD

**Issue by hiddentao** [sindresorhus/awesome-scifi#50]
As discussed in #46 I am of the opinion that for any item, the synopsis should come before the commentary. This fits the usual pattern of "what it is" followed by "why I should read/view it", just like any online item page (e.g. on Amazon you see title, brief synopsis, and then user reviews)..

Thoughts welcome.

**Comment by RichardLitt** [comment]
Thanks @hiddentao. 

I think that the commentary should come before, because generally: 
 * There's only one commentary, which means that it is short and to the point.
 * Anyone can read the synopsis anywhere - most of the time it is taken directly from Goodreads or Wikipedia. It's only here to give some broad analysis, but people are really here to know who - on GitHub, as a coder interested in open source lists - likes what, and why. It's our central purpose. 
 * I think it looks nicer. Not the best reason, but it's there.

**Comment by elssar** [comment]
I think this hinges on whether there is a limit on the number of commentaries per entry, and also have a character limit on the commentary.

If five people add a commentary for an item, the synopsis will get buried under them. Likewise if someone writes an essay of a commentary.

Finally, we need to consider what is more relevant to the people consuming this list - commentary from someone who has already read/watched the entry, or a synopsis.

One concern I have is that the quality and content of the commentary would not be uniform. Something like _"This book changed my life"_ or _"Best SF I've ever read"_ isn't really helpful.

**Comment by RichardLitt** [comment]
Agreed on the number of commentaries being a thing. But I think we can cross that road when we get to it - right now, it seems fine to me. No one has added a double commentary, and it seems like over optimization to plan that in advance. 

I agree that the commentary isn't uniform. We can deal with that in the pull requests.

**Comment by sindresorhus** [comment]
I like having the commentary first. It's a nice foretaste before reading the more in-depth synopsis.

**Comment by RichardLitt** [comment]
I think the consensus is to have commentary first. Thanks @hiddentao anyway. :)

**Comment by hiddentao** [comment]
No problem!
